language: android

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

env:
  global:
    - GRADLE_OPTS="-Xms128m"

script:
  - ./gradlew clean assemble test --tests com.google.protobuf.gradle.plugins.ProtobufJavaPluginTest --stacktrace
  - ./gradlew test --tests com.google.protobuf.gradle.plugins.ProtobufAndroidPluginTest --stacktrace
  - ./gradlew codenarcMain || (cat ./build/reports/codenarc/main.txt && false)
  - ./gradlew codenarcTest || (cat ./build/reports/codenarc/test.txt && false)

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
