name: GitHub Actions Linux Testing

on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build
      run: .github/workflows/testing.sh
